Add system prerequisites session to readme
Unity-Technologies/runtime pull request #105
Opened 2023-01-30 17:39 UTC by yuc434

Add a link referring to the environment requirements

2023-01-30 18:55 UTC, scott-ferguson-unity requested changes

2023-01-30 18:55 UTC, scott-ferguson-unity commented on unity/README.md
> +https://github.com/dotnet/runtime/tree/main/docs/workflow/requirements
Could you make this a mark down link so it's clickable?

I think the following should work:

Please refer to [this page](https://github.com/dotnet/runtime/tree/main/docs/workflow/requirements) for environment requirements before building.

2023-01-31 15:34 UTC, scott-ferguson-unity approved these changes

2023-01-31 16:31 UTC, joshpeterson approved these changes

2023-01-31 18:37 UTC, merged