Add a UnityAot MSBuild option for Mono's System.Private.CoreLib
Unity-Technologies/runtime pull request #272
Opened 2024-10-28 14:25 UTC by scott-ferguson-unity

IL2CPP is currently using the Mono System.Private.CoreLib implementation, but it contains some AOT unfriendly code paths.  We instead want to be able to use the NativeAot version of ArraySortHelper.

This adds an UnityAot property that we can use to conditionally include files.  It also adds an UNITY_AOT compilation define that we can use.

2024-10-28 15:20 UTC, mrvoorhe commented
What would it look like if we moved all the logic into a `System.Private.CoreLib.props` file somewhere under the `unity` root directory and then imported just the props file in [System.Private.CoreLib.csproj](https://github.com/Unity-Technologies/runtime/pull/272/files#diff-4accdf2622952296e1e5354de533c41c4b6cf2b2678ca800e47c6548ca2e9aa9) ?

If it's doable, the advantages would be
1) Easier to review our customizations at a glance
2) Minimizes the changes to `System.Private.CoreLib.csproj` which will reduce the odds of conflicts.

2024-10-29 16:22 UTC, scott-ferguson-unity commented
> What would it look like if we moved all the logic into a `System.Private.CoreLib.props` file somewhere under the `unity` root directory and then imported just the props file in [System.Private.CoreLib.csproj](https://github.com/Unity-Technologies/runtime/pull/272/files#diff-4accdf2622952296e1e5354de533c41c4b6cf2b2678ca800e47c6548ca2e9aa9) ?

@mrvoorhe - I've done that - it does clean some things up a bit.

2024-10-29 17:39 UTC, mrvoorhe requested changes

2024-10-29 17:39 UTC, mrvoorhe commented on src/mono/System.Private.CoreLib/System.Private.CoreLib.csproj
> +      <Compile Include="$(BclSourcesRoot)\System\Collections\Generic\ArraySortHelper.Mono.cs" Condition="'$(UnityAot)' != 'true'" />
I think you can move this to `unity-aot.props` as well.  Try using something like
```
Compile Exclude="$(BclSourcesRoot)\System\Collections\Generic\ArraySortHelper.Mono.cs"
```

2024-10-29 17:39 UTC, mrvoorhe commented on unity/unity-sources/Runtime/Mono/unity-aot.props
> +<Project Sdk="Microsoft.NET.Sdk">
I was thinking a different file structure.  Something like
```
unity\unityaot-props\System.Private.CoreLib.props
unity\unityaot-props\System.Linq.props
```

It doesn't seem like the current organization would scale once we have to do this in another csproj?  Or am I missing how that would work?

2024-10-30 13:55 UTC, mrvoorhe approved these changes
Nice.  Looks minimally invasive.

2024-10-30 13:56 UTC, mrvoorhe commented
Maybe hold off merging until you can confirm this PR didn't break `Test - Runtime & Pal - Linux x64 Debug`.  The last run on `main` was in late September and it was green.  I started a new run

 https://unity-ci.cds.internal.unity3d.com/project/1674/branch/unity-main/jobDefinition/.yamato%2Fruntime-and-pal-tests.yml%23test_-_runtime__pal_-_linux_x64_debug?nav=branches

2024-10-30 15:26 UTC, mrvoorhe commented
The job passed on `unity-main` https://unity-ci.cds.internal.unity3d.com/job/43049025 so it appears this PR is somehow breaking something?

2024-11-04 20:05 UTC, scott-ferguson-unity commented
> The job passed on `unity-main` https://unity-ci.cds.internal.unity3d.com/job/43049025 so it appears this PR is somehow breaking something?

I reran this and it passed.

2024-11-05 20:41 UTC, joncham approved these changes

2024-11-07 12:57 UTC, merged